# Importing the needed libraries

In [3]:
import numpy as np
from keras.datasets import imdb
import tensorflow as tf 
from tensorflow.keras.layers import Dense, Flatten, Activation, Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import TensorBoard  
import matplotlib.pyplot as plt



Using TensorFlow backend.


# Loading the preloaded dataset from keras.datasets 

In [4]:
'''Loading the Preloaded Data'''

# call load_data with allow_pickle implicitly set to true
(training_data, training_targets), (testing_data, testing_targets) = imdb.load_data(num_words=10000)

In [6]:
#Concatenating the data and targets
data = np.concatenate((training_data, testing_data), axis=0)
targets = np.concatenate((training_targets, testing_targets), axis=0)

Vectorising the data and coverting list objects

In [7]:
#Vectorising
def vectorize(sequences, dimension = 10000):
 results = np.zeros((len(sequences), dimension))
 for i, sequence in enumerate(sequences):
  results[i, sequence] = 1
 return results

#Calling the vectorise function
data = vectorize(data)

Splitting the data into Training and Testing sets

In [8]:
targets = np.array(targets).astype("float32")
X_test = data[:10000]
y_test = targets[:10000]
X_train = data[10000:]
y_train = targets[10000:]

In [9]:
''' Analysinig the data set and reallocating'''
print(X_train.shape)
print(X_train)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(40000, 10000)
[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]
(10000, 10000)
(40000,)
(10000,)


# Constructing the deep neural network

In [12]:

model =Sequential()
# Input - Layer
model.add(Dense(50, activation = "relu", input_shape=(10000, )))
# Hidden - Layers
model.add(Dropout(0.3, noise_shape=None, seed=None))
model.add(Dense(50, activation = "relu"))
model.add(Dropout(0.2, noise_shape=None, seed=None))
model.add(Dense(50, activation = "relu"))
# Output- Layer
model.add(Dense(1, activation = "sigmoid"))

model.summary()

model.compile(loss='binary_crossentropy', optimizer= 'adam', metrics=['accuracy'])
#Fitting the model 
fitted_model = model.fit(X_train, y_train, epochs = 2, batch_size =500, validation_data = (X_test,y_test))



Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 50)                500050    
_________________________________________________________________
dropout_4 (Dropout)          (None, 50)                0         
_________________________________________________________________
dense_9 (Dense)              (None, 50)                2550      
_________________________________________________________________
dropout_5 (Dropout)          (None, 50)                0         
_________________________________________________________________
dense_10 (Dense)             (None, 50)                2550      
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 51        
Total params: 505,201
Trainable params: 505,201
Non-trainable params: 0
________________________________________________

# Calculating the validation accuracy


In [13]:
print("Test-Accuracy:", np.mean(fitted_model.history["val_accuracy"]))

Test-Accuracy: 0.8954499959945679
